In [6]:
import numpy as np

In [7]:
D = np.array([[0.2, 2], [0.3, 4], [0.5, -1], [0.7, 6]])

In [9]:

print("Covariance matrix of x:\n", np.cov(D))

Covariance matrix of x:
 [[ 1.62   3.33  -1.35   4.77 ]
 [ 3.33   6.845 -2.775  9.805]
 [-1.35  -2.775  1.125 -3.975]
 [ 4.77   9.805 -3.975 14.045]]


In [10]:
def covariance(x, y):
    # Finding the mean of the series x and y
    mean_x = sum(x)/float(len(x))
    mean_y = sum(y)/float(len(y))
    # Subtracting mean from the individual elements
    sub_x = [i - mean_x for i in x]
    sub_y = [i - mean_y for i in y]
    numerator = sum([sub_x[i]*sub_y[i] for i in range(len(sub_x))])
    denominator = len(x)-1
    cov = numerator/denominator
    return cov

In [11]:
x = [0.2, 0.3, 0.5, 0.7]

In [12]:
y = [2, 4, -1, 6]

In [13]:
covariance(x, y)

0.2083333333333333

In [15]:
a = np.array([1,-1,-2,4])

In [16]:
np.transpose(a)

array([ 1, -1, -2,  4])

In [17]:
b = np.array([2,-1,-1,3])

In [18]:
np.dot(np.transpose(a), b)

17

In [20]:
import math

In [21]:
math.dist(a,b)

1.7320508075688772

In [22]:
x3 = [1.8, 0.5, 5.2, 3]

In [23]:
x4 = [5.6, 0.8, 5.1, 1]

In [24]:
math.dist(x3, x4)

4.305810028322197

In [25]:
str1 = "ABCABCC"

In [26]:
str2 = "HLLLHLH"

In [27]:
def hammingDist(str1, str2):
    i = 0
    count = 0
 
    while(i < len(str1)):
        if(str1[i] != str2[i]):
            count += 1
        i += 1
    return count

In [28]:
hammingDist(str1, str2)

7

In [31]:
import pandas as pd

In [32]:
data = [["A","H"], ["B", "L"], ["C", "L"], ["A", "L"], ["B","H"], ["C", "L"], ["C", "H"]]

In [50]:
df = pd.DataFrame(data, columns=['X1', 'X2'])
df

X1 X2
0  A  H
1  B  L
2  C  L
3  A  L
4  B  H
5  C  L
6  C  H

In [57]:
df['X1'] = df['X1'].astype('category')
df['X1_new'] = df['X1'].cat.codes

In [58]:
df['X2'] = df['X2'].astype('category')
# Assigning numerical values and storing it in another columns
df['X2_new'] = df['X2'].cat.codes

In [78]:
from sklearn.preprocessing import OneHotEncoder


In [60]:
# Create an instance of One-hot-encoder
enc = OneHotEncoder()

In [66]:
  
# Passing encoded columns
enc_data = pd.DataFrame(enc.fit_transform(
    df[['X1_new', 'X2_new']]).toarray())
enc_data

0    1    2    3    4
0  1.0  0.0  0.0  1.0  0.0
1  0.0  1.0  0.0  0.0  1.0
2  0.0  0.0  1.0  0.0  1.0
3  1.0  0.0  0.0  0.0  1.0
4  0.0  1.0  0.0  1.0  0.0
5  0.0  0.0  1.0  0.0  1.0
6  0.0  0.0  1.0  1.0  0.0

In [64]:
# Merge with main
New_df = df.join(enc_data)
  
print(New_df)

  X1 X2  X2_new  X1_new    0    1    2    3    4
0  A  H       0       0  1.0  0.0  0.0  1.0  0.0
1  B  L       1       1  0.0  1.0  0.0  0.0  1.0
2  C  L       1       2  0.0  0.0  1.0  0.0  1.0
3  A  L       1       0  1.0  0.0  0.0  0.0  1.0
4  B  H       0       1  0.0  1.0  0.0  1.0  0.0
5  C  L       1       2  0.0  0.0  1.0  0.0  1.0
6  C  H       0       2  0.0  0.0  1.0  1.0  0.0


In [67]:
math.dist(enc_data.iloc[5], enc_data.iloc[6])

1.4142135623730951

In [70]:
x6 = np.array([1,2])
x7 = np.array([0,2])

In [69]:
from scipy.spatial.distance import hamming

In [71]:
hamming(x6, x7) * len(x6)

1.0

In [72]:
x6 = np.array([0.0, 0.0,  1.0,  0.0,  1.0])

In [73]:
x7 = np.array([0.0,  0.0,  1.0,  1.0,  0.0])

In [74]:
hamming(x6, x7) * len(x6)

2.0

In [81]:
from sklearn.metrics import DistanceMetric as _DistanceMetric

In [82]:
df = pd.DataFrame([[0.2,23,5.7,'A'],[0.4,1,5.4,'B'],[1.8,0.5,5.2,'C'],[5.6,50,5.1,'A'],[-0.5,34,5.3,'B'],[0.4,19,5.4,'C'],[1.1,11,5.5,'C']])

In [83]:
df

0     1    2  3
0  0.2  23.0  5.7  A
1  0.4   1.0  5.4  B
2  1.8   0.5  5.2  C
3  5.6  50.0  5.1  A
4 -0.5  34.0  5.3  B
5  0.4  19.0  5.4  C
6  1.1  11.0  5.5  C

In [84]:
df.columns = ['X1','X2','X3','X4']

In [85]:
df

X1    X2   X3 X4
0  0.2  23.0  5.7  A
1  0.4   1.0  5.4  B
2  1.8   0.5  5.2  C
3  5.6  50.0  5.1  A
4 -0.5  34.0  5.3  B
5  0.4  19.0  5.4  C
6  1.1  11.0  5.5  C

In [86]:
s1 = _DistanceMetric.get_metric('manhattan').pairwise(df[['X1']])

In [88]:
s1 = s1/max(np.ptp(df['X1']),1)
s1

array([[0.        , 0.0053749 , 0.04299919, 0.14512228, 0.01881215,
        0.0053749 , 0.02418705],
       [0.0053749 , 0.        , 0.03762429, 0.13974738, 0.02418705,
        0.        , 0.01881215],
       [0.04299919, 0.03762429, 0.        , 0.10212309, 0.06181134,
        0.03762429, 0.01881215],
       [0.14512228, 0.13974738, 0.10212309, 0.        , 0.16393443,
        0.13974738, 0.12093523],
       [0.01881215, 0.02418705, 0.06181134, 0.16393443, 0.        ,
        0.02418705, 0.04299919],
       [0.0053749 , 0.        , 0.03762429, 0.13974738, 0.02418705,
        0.        , 0.01881215],
       [0.02418705, 0.01881215, 0.01881215, 0.12093523, 0.04299919,
        0.01881215, 0.        ]])

In [91]:
s2 = _DistanceMetric.get_metric('manhattan').pairwise(df[['X2']])/max(np.ptp(df['X2']),1)
s2

array([[0.        , 0.44444444, 0.45454545, 0.54545455, 0.22222222,
        0.08080808, 0.24242424],
       [0.44444444, 0.        , 0.01010101, 0.98989899, 0.66666667,
        0.36363636, 0.2020202 ],
       [0.45454545, 0.01010101, 0.        , 1.        , 0.67676768,
        0.37373737, 0.21212121],
       [0.54545455, 0.98989899, 1.        , 0.        , 0.32323232,
        0.62626263, 0.78787879],
       [0.22222222, 0.66666667, 0.67676768, 0.32323232, 0.        ,
        0.3030303 , 0.46464646],
       [0.08080808, 0.36363636, 0.37373737, 0.62626263, 0.3030303 ,
        0.        , 0.16161616],
       [0.24242424, 0.2020202 , 0.21212121, 0.78787879, 0.46464646,
        0.16161616, 0.        ]])

In [92]:
s3 = _DistanceMetric.get_metric('manhattan').pairwise(df[['X3']])/max(np.ptp(df['X3']),1)

In [94]:
pip install gower

Note: you may need to restart the kernel to use updated packages.


In [95]:
gower.gower_matrix(df)

NameError: name 'gower' is not defined

In [96]:
import gower
gower.gower_matrix(df)

array([[0.        , 0.49430782, 0.63754344, 0.6076751 , 0.5009107 ,
        0.40339872, 0.43082464],
       [0.49430782, 0.        , 0.39323562, 0.83558947, 0.24521858,
        0.3409091 , 0.37086025],
       [0.63754344, 0.39323562, 0.        , 0.6974044 , 0.5551209 ,
        0.23414472, 0.20671882],
       [0.6076751 , 0.83558947, 0.6974044 , 0.        , 0.6641414 ,
        0.7446804 , 0.79806256],
       [0.5009107 , 0.24521858, 0.5551209 , 0.6641414 , 0.        ,
        0.40430948, 0.5150687 ],
       [0.40339872, 0.3409091 , 0.23414472, 0.7446804 , 0.40430948,
        0.        , 0.11075923],
       [0.43082464, 0.37086025, 0.20671882, 0.79806256, 0.5150687 ,
        0.11075923, 0.        ]], dtype=float32)

In [97]:
# Gower's distance can be used to measure how different two records are. The records may contain combinations of logical, numerical, categorical or text data. The distance is always a number between 0 (identical) and 1 (maximally dis- similar).

In [ ]:
# Jaccard Similarity value ranges from 0 to 1. The higher the number, the more similar are the datasets with each other.